version: 0.0
os: linux
files:
  - source: /
    destination: /eb/web 
hook:
 BeforeInstall:
  - location: script/make_time
    timeout: 300
    runas: root
 AfterInstall:
  - location: script/change_time
    timeout: 300
    runas: root
